### ISSUE TITLE
HEX-код для бінарного коду

### ISSUE THREAD

**Issue by indrekis** [dariaomelkina/poc_project#4]
Додайте, будь ласка, можливість чи то переключитися на HEX, чи то його виводити поруч -- вже обіцяєте його. :-) Та й було б зручно.

![image](https://user-images.githubusercontent.com/26859944/107424521-6dccce00-6b26-11eb-9b07-413d4759da1a.png)

**Comment by dariaomelkina** [comment]
Переключення мало б давно працювати: при нажатті на HEX воно як раз і відбувається.
Зараз спробувала, у Firefox точно працює, можливо в інших браузерах виникли проблеми.

**Comment by indrekis** [comment]
Працює, дякую -- я певне знову щось не так робив (як вже бувало -- поговорю із вами і все ОК стає).
